### ISSUE TITLE
Failed assertion: line 69 pos 15: 'color != null': is not true.

### ISSUE THREAD

**Issue by isaacdarcilla** [david-legend/otp_textfield#1]
import 'package:flutter/material.dart';
import 'package:flutter_otp_text_field/flutter_otp_text_field.dart';

class OtpScreen extends StatefulWidget {
  @override
  _OtpState createState() => _OtpState();
}

class _OtpState extends State<OtpScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        // leading: IconButton(
        //   icon: Icon(
        //     Icons.keyboard_backspace,
        //   ),
        //   onPressed: ()=>Navigator.pop(context),
        // ),
        centerTitle: true,
        title: Text(
          "OTP",
        ),
        elevation: 0.0,
      ),

      body: Container(
        child: Padding(
          padding: EdgeInsets.all(8.0),
          child: OtpTextField(
            numberOfFields: 5,
            borderColor: Color(0xFF512DA8),
            showFieldAsBox: true,
            onCodeChanged: (String value) {

            },
            onSubmit: (String verificationCode){
              //navigate to different screen code goes here
              showDialog(
                  context: context,
                  builder: (context){
                    return AlertDialog(
                      title: Text("Verification Code"),
                      content: Text('Code entered is $verificationCode'),
                    );
                  }
              );
            }, // end onSubmit
          ), // end PinEntryTextField()
        ), // end Padding()
      ), 
    );
  }
}

My code

**Comment by Hasilt** [comment]
In my case giving `enabledBorderColor` a color value solved the issue.

**Comment by david-legend** [comment]
looks like I should provide a default value for enabledBorderColor - will do that and update the package. Thanks
