### ISSUE TITLE
Not able to go back in previous otp filed when press back button

### ISSUE THREAD

**Issue by aman246149** [david-legend/otp_textfield#12]
suppose i have 6 otp filled  and i enter 4 otp number  but now i want to go to previous otp filled by pressing back button how to achieve this

**Comment by david-legend** [comment]
I have not exposed a function for that.
I am guessing your UI requires that you have such control ?

**Comment by prkhrv** [comment]
@david-legend @aman246149  It can be achieved with some little modifications in the current implementation, I will try to update it tomorrow.

**Comment by aman246149** [comment]
Thanks sir

**Comment by ADLsourceCode** [comment]
@prkhrv  is this resolved ?

**Comment by RiyasTp** [comment]
no

**Comment by RiyasTp** [comment]
issue is not yet resolved

**Comment by prkhrv** [comment]
Hi @RiyasTp Unfortunately, I haven't got time to fix it yet.

**Comment by Kishandobariya76** [comment]
please resolved this issue

**Comment by eyos-ias** [comment]
> Hi @RiyasTp Unfortunately, I haven't got time to fix it yet.

skill issue

**Comment by david-legend** [comment]
I have merged the PR, publishing soon
