### ISSUE TITLE
Textfield backbutton 

### ISSUE THREAD

**Issue by sivasankar2221** [david-legend/otp_textfield#32]
When user try to clear the particular value like i have numberOfFields 6  
 users typed   1 2 3 4   need to clear the 4th but cursor moved to  3rd 
 Clear the in between the textfield (Mobile)

**Comment by BrunoJay** [comment]
Experienced the same issue

**Comment by david-legend** [comment]
anyone opening a PR ?

**Comment by HARSHILITALIYA16** [comment]
I am also troubled by this problem.

https://github.com/user-attachments/assets/86e3e730-1be2-470e-ad84-63216097bf01

**Comment by david-legend** [comment]
Will fix it on the weekend and realease and new version

**Comment by HARSHILITALIYA16** [comment]
Thank you!
I hope you resolve this as soon as possible.

**Comment by david-legend** [comment]
Will do
