### ISSUE TITLE
Unable to jump between fields when deleting

### ISSUE THREAD

**Issue by abisao1** [david-legend/otp_textfield#4]
Cant automatically jump to the previous textbox when deleting. I have to delete one by clicking on each textbox.

**Comment by a7md0** [comment]
I have the same behavior, not sure if it's a bug or a non implemented feature

**Comment by AshishAcharya083** [comment]
Same behavior. Please fix it soon

**Comment by phillipjacobs** [comment]
I don't think this is a bug. I think this feature still needs to be built. Will definitely be a good feature to add.

**Comment by khayargoli** [comment]
yes please highly demanded.!!!!

**Comment by david-legend** [comment]
Will look at it early tomorrow, will let you know when I add the feature

**Comment by prkhrv** [comment]
Yeah, need the feature too.

**Comment by khayargoli** [comment]
> Will look at it early tomorrow, will let you know when I add the feature

Sure 😃

**Comment by prkhrv** [comment]
@david-legend  Added a PR to fix issue #11 .

**Comment by david-legend** [comment]
Thanks @prkhrv
Been busy with something else, never got to it.
Thanks a lot, I have merged the PR and published

**Comment by david-legend** [comment]
We can consider this issue closed!!!!

**Comment by khayargoli** [comment]
Wow David is a LEGEND 👍

😅

**Comment by utariddev** [comment]
can someone provide an example please ?

**Comment by abisao1** [comment]
For example if you entered wrong values for you to delete you have to
manually put cursor in each of the textfield and delete. What I would love
is to automatically delete values backwards.
