### ISSUE TITLE
Can't add controller

### ISSUE THREAD

**Issue by Davete0302** [david-legend/otp_textfield#9]
Would want to clear textfield

**Comment by phillipjacobs** [comment]
I agree with @Davete0302. I know it's trick because there's essentially many text fields, so a custom controller would do.

**Comment by david-legend** [comment]
Will look into this. Should add a fix in a few days

**Comment by ramachandra9345** [comment]
Any update on this please

**Comment by ramachandra9345** [comment]
Hello
I need fix for this. Could you please add fix ASAP

**Comment by david-legend** [comment]
I will look at it over the weekend. Sorry for the delay. Got so busy with work

**Comment by david-legend** [comment]
@ramachandra9345 @phillipjacobs @Davete0302 

Sorry for the delay. But I have updated the api.
You should be able to clear text now. ANd I have also exposed the textControllers for every textField
